In [1]:
import torch

/Users/akhtar/opt/anaconda3/envs/condatorch/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [54]:
pred = torch.rand(4, 5, 512, 512)
#pred = torch.softmax(pred, dim=1)

In [55]:
pred.shape

torch.Size([4, 5, 512, 512])

In [56]:
p = torch.sum(pred, dim=(2, 3)) / (512 * 512)

In [57]:
p

tensor([[0.4996, 0.5008, 0.5004, 0.4995, 0.5010],
        [0.5004, 0.4999, 0.5002, 0.5005, 0.5003],
        [0.4994, 0.5000, 0.5007, 0.4996, 0.4998],
        [0.5001, 0.4998, 0.4997, 0.5009, 0.5000]])

In [58]:
y = torch.mean(pred, dim=(2,3)) 

In [59]:
y

tensor([[0.4996, 0.5008, 0.5004, 0.4995, 0.5010],
        [0.5004, 0.4999, 0.5002, 0.5005, 0.5003],
        [0.4994, 0.5000, 0.5007, 0.4996, 0.4998],
        [0.5001, 0.4998, 0.4997, 0.5009, 0.5000]])

In [40]:
x = torch.mean(pred, dim=(2, 3))
x = x / torch.sum(x, dim=1, keepdim=True)

In [41]:
x

tensor([[0.2001, 0.2001, 0.1998, 0.1999, 0.2001],
        [0.1997, 0.2001, 0.2001, 0.2000, 0.2000],
        [0.1997, 0.2001, 0.1998, 0.2002, 0.2002],
        [0.1999, 0.2001, 0.2001, 0.2001, 0.1998]])

In [42]:
z = pred.sum(dim=(2,3))
z = z / z.sum(dim=1, keepdim=True)

In [43]:
z

tensor([[0.2001, 0.2001, 0.1998, 0.1999, 0.2001],
        [0.1997, 0.2001, 0.2001, 0.2000, 0.2000],
        [0.1997, 0.2001, 0.1998, 0.2002, 0.2002],
        [0.1999, 0.2001, 0.2001, 0.2001, 0.1998]])

In [52]:
l = pred.mean(dim=2).mean(dim=2)

In [53]:
l

tensor([[0.5003, 0.5003, 0.4997, 0.5000, 0.5003],
        [0.4987, 0.4997, 0.4997, 0.4994, 0.4994],
        [0.4991, 0.5001, 0.4993, 0.5005, 0.5004],
        [0.4998, 0.5003, 0.5004, 0.5003, 0.4995]])